[workspace]
members = ["jupiter-swap-api-client", "example"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
solana-account-decoder = "2.2.0"
solana-sdk = "2.2.0"
solana-client = "2.2.0"
